@startuml
object User {
 uid: varchar(20) (PK)
 status: enum
 last_login: Datetime
 first_login: Datetime
}

object Keyword {
 key: varchar(20) (PK)
 html_url: varchar(255)
 result_count: integer
 search_duration: integer
 ads_words_count: integer
 url_count: smallint
 created_at: Datetime
}

object UserSearch {
 id: serial (PK)
 uuid: varchar(20) (FK)
 keyword_id: varchar(20) (FK)
 created_at: Datetime
}

User o-- Keyword
Keyword --o UserSearch
@enduml